# Generated by Django 2.1.5 on 2019-12-30 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='descriptions',
            field=models.TextField(blank=True),
        ),
    ]
